### ISSUE TITLE
examples/pgsql/kamailio.cfg:144, 191-233 Fills logs with errors+warnings due to DB unique constraint failures

### ISSUE THREAD

**Issue by quentusrex** [sipcapture/homer-api#122]
insert into stats_ip_mem fails due to:
stats_ip_mem_datemethod when a user behind a single ip registers multiple times from the same ip. By the name, this looks like it might have needed to have the DB constraint include a date. This might be a table construction issue in the table rotate script.

insert into stats_useragent_mem fails due to:
stats_user_agent_mem_useragent constraint which requires unique combination of (useragent, method)

**Comment by simplevoip** [comment]
The example MySQL kamailio.cfg has "ON DUPLICATE KEY UPDATE" clauses in most of its INSERTs. The example Postgres kamailio.cfg does not. This is because Postgres doesn't support that clause.

Postgres >9.5 DOES, however, allow for handling of duplicates like the following:

 `INSERT INTO stats_ip_mem (method, source_ip, total) VALUES('INVITE', '8.8.8.8', 1) ON CONFLICT (method, source_ip) DO UPDATE SET total=stats_ip_mem.total+1;`

I am rewriting my kamailio.cfg to update on conflict ("upsert") for all of the appropriate INSERTS, basing that assessment on what's upserted in the MySQL config. If there's interest, I can submit a PR with those queries rewritten, which should make it easier for others to get this working in Postgres. I found a few other quirks in the pgsql templates I could fix, as well (e.g. user creation SQL script uses `crypt('<pass_string>', gen_salt('md5'))` for the passwords, while the actual API is checking passwords using `crypt('<pass_string>', 'password')`).

**Comment by lmangani** [comment]
@quentusrex you might really really really want to consider H7, its pgsql native

**Comment by adubovikov** [comment]
http://install.sipcapture.io/
