### ISSUE TITLE
homer-api not connecting to the database

### ISSUE THREAD

**Issue by Julian-Mentasti** [sipcapture/homer-api#181]
Hey, 

I'm running homer 5.05, and a heplify-server on debian 8.10. My database is 5.7.22 MySQL Community heplify-server. The server is able to send the data to the database however, when I load the homer-ui it appears no calls have been registered. 

I looked into the preferences.php and configuration.php I couldn't find anything odd. But, for all I know the problem is not here.

Thanks !

**Comment by negbie** [comment]
@Julian-Mentasti I made a homer5+heplify-server manual installation guide. See here:
https://github.com/sipcapture/heplify-server/tree/master/example/install/homer5

This should be easy to follow and since I made it on digital ocean with a clean debian 9.4 x64 droplet its reproducible. So when you followed this guide and something does not work you did a mistake. Simply take a closer look and repeat.

**Comment by negbie** [comment]
Keep in mind that this is just a basic installation and you should consider to do following:
* change mysql root credentials
* setup ssl + nginx
* change some parameters inside /var/www/html/api/preferences.php like(RTCP_TABLE_PARTITION,NORMALIZE_NUMBER)
* take a look at grafana + prometheus
* change some folder permissions inside /var/www/html to be able to store dashboards
* set some heplify-server options like DBDropDays = 7

I'am to lazy to write for all of this a guide so google is you best friend from now on ;)

**Comment by Julian-Mentasti** [comment]
Thanks a lot on the guide negbie! It was supper helpful.
