### ISSUE TITLE
Time-sufixed tables complex search

### ISSUE THREAD

**Issue by kvishnivetsky** [sipcapture/homer-api#22]
Now we search in tables like this:
1. set OVERAL limit to 200
2. select from table calls,
3. decrease limit for result rows count
4. if limit is still > 0 then we select from table registrations
5. decrease limit for result rows count
6. if limit is still > 0 then we select from table rest
7. return results

Ok. User defined a "time rage" as a criteria in search request, so, he expects, that software will return all packets from defined time rage, but not more then "result limit"(200).
What we have in reality? We have an issue, because there will be no results from the second and the third tables included in response if select query from the first table will return >= 200 records. but it IS incorrect behavior because of there are records in those 2 tables, that match query criteria and have higher priority by time filed, but they will not be included in query results.
I see a solution in UNITE query with ordering by time filed or in SELECT/INSERT to temporary(memory) table and then select from it with LIMIT and ORDER.

**Comment by kvishnivetsky** [comment]
Another solution is to change DB design from "large, flat table with TEXT(call-id,tags,from/to users) searches on it", to a set of tables, reflecting possible search criteria. The purpose of this is to substitute "text search" with "integer JOINING" and subset of special, optimized, criteria dependent queries. It will make more complex WRITE operation, but will make "lighter" READing.

**Comment by adubovikov** [comment]
yes, this can be bad for "NORMAL DB" operation, but here we are talking about calls/registrations transactions. So, how it works in the real life:
1. NOC has a ticket: calls or registrations doesn't work.
   2.
   a. NOC checks calls OR registrations ( first logical sharding) + time range (second logical sharding)
   or 
   b. NOC can search in all transactions(call, registrations, rest) for specific the time range (logical sharding) + user id (RURI, FROM, PAI)  (index scope)

in the both cases the result will be smaller than this limit and will absolutely compatible with "NOC's logic"

create temporally mysql's table and do order/limit inside make for me no sense, because much quicker and better manipulate with results inside php: concatenate results and do sorting  (we do usort already). This is also correct way for multiple DB nodes.

maximum that we can do, it's create special API call and do inside aggregation for each transaction with original limit,  sort it and return limited data.

**Comment by kvishnivetsky** [comment]
Ok, thanks. Now I see and will assume "NOC logic" as a basement.
It seems to me, that I am to implement a solution with "aggregation and sorting inside of PHP scripts" to match user's expectations.

BTW: I think, it would be great to release a document with "NOC logic" description in git repo to prevent such questions in future. A simple "How to".

**Comment by adubovikov** [comment]
sure, we will do it asap, please don't hesitate contact me in gtalk :-) we can also discuss there.

**Comment by kvishnivetsky** [comment]
Ok. See you there.
